language: c
dist: trusty
sudo: required
before_install:
  - sudo apt-get install python2.7 python-numpy python-pip
script: pip install numpy && ./demo.sh | tee results.txt && [[ `cat results.txt  | grep 'Total accuracy' | sed -n '/2[1..5]./p' | wc -l` = "1" ]] && echo test-passed
